name: 2 Deploy Site on push
on:
  push:
    branches:
      - master
      - develop
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
     
    steps:
    - name: Get the latest code
      uses: actions/checkout@v3.5.3
      with:
          php-version: '8.2'
    - name: Install Dependencies
      run: | 
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
                                
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: cpl-l.x10.mx
        username: ${{ secrets.CPLL_USER_FTP}}
        password: ${{ secrets.CPLL_PASS_FTP}}
        server-dir: ./domains/cpl-l.x10.mx/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/tests*
          **/tests/**
